#!/bin/sh /etc/rc.common

START=25

boot() {
	eth_cpu_affinity
}

start() {
	eth_cpu_affinity
}

eth_cpu_affinity() {
	# eth0
	echo 2 > /proc/irq/36/smp_affinity
	# eth1
	echo 2 > /proc/irq/37/smp_affinity
}
