#!/bin/sh /etc/rc.common

START=15

boot() {
	if [ -f "/proc/irq/104/smp_affinity" ]; then
		echo 8 > /proc/irq/104/smp_affinity
		echo 4 > /proc/irq/129/smp_affinity
		echo 2 > /proc/irq/134/smp_affinity
	else
		echo 8 > /proc/irq/103/smp_affinity
		echo 4 > /proc/irq/128/smp_affinity
		echo 2 > /proc/irq/133/smp_affinity
	fi
}
